import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,CalendarClock,CheckCircle2,Clock3,CreditCard,ShieldAlert} from 'lucide-react';
import {extensionsApi} from '../../services/api';

const fmt=v=>v?new Date(v).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
const money=n=>`${Number(n||0).toLocaleString('vi-VN')} ₫`;
const localInput=v=>{if(!v)return'';const d=new Date(v),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`};
export default function ExtendRentalPage({onNavigate,initialData}){
 const contract=initialData?.contract||initialData||null;
 const [newTime,setNewTime]=useState(''); const [reason,setReason]=useState(''); const [rows,setRows]=useState([]); const [busy,setBusy]=useState(false); const [err,setErr]=useState(''); const [msg,setMsg]=useState('');
 const latest=rows[0];
 const days=useMemo(()=>{if(!contract?.thoiGianTraDuKien||!newTime)return 0;return Math.max(1,Math.ceil((new Date(newTime)-new Date(contract.thoiGianTraDuKien))/86400000));},[newTime,contract]);
 const estimate=days*Number(contract?.donGiaNgay||0);
 const load=async()=>{if(!contract?.id)return;try{const r=await extensionsApi.myByContract(contract.id);setRows((Array.isArray(r)?r:[]).sort((a,b)=>Number(b.id)-Number(a.id)));}catch(e){setErr(`${e.status||''} ${e.message}`.trim())}};
 useEffect(()=>{if(contract){setNewTime(localInput(contract.thoiGianTraDuKien));load();}},[contract?.id]);useEffect(()=>{const f=()=>load();window.addEventListener('carrent:remote-update',f);return()=>window.removeEventListener('carrent:remote-update',f)},[contract?.id]);
 const submit=async()=>{if(!contract?.id)return; if(new Date(newTime)<=new Date(contract.thoiGianTraDuKien)){setErr('Thời gian trả mới phải sau thời gian trả hiện tại.');return;} try{setBusy(true);setErr('');const r=await extensionsApi.create({idHopDong:contract.id,thoiGianTraMoi:new Date(newTime).toISOString(),lyDo:reason});setMsg('Đã gửi yêu cầu gia hạn. Nhân viên sẽ kiểm tra và xử lý.');setRows([r,...rows]);}catch(e){setErr(`${e.status||''} ${e.message}`.trim())}finally{setBusy(false)}};
 if(!contract)return <div className="min-h-screen bg-[#F6F8FB] p-6"><div className="max-w-3xl mx-auto bg-white border rounded-2xl p-6"><button onClick={()=>onNavigate('contract')} className="text-gray-500">← Hợp đồng</button><h1 className="text-2xl font-bold mt-5">Gia hạn hợp đồng</h1><p className="text-gray-500 mt-2">Vui lòng mở một hợp đồng đang thuê và chọn “Gia hạn hợp đồng”.</p></div></div>;
 return <div className="min-h-screen bg-[#F6F8FB] p-5"><div className="max-w-4xl mx-auto"><button onClick={()=>onNavigate('tracking',{idYeuCau:contract.idYeuCauThue})} className="flex items-center gap-2 text-gray-500 mb-5"><ArrowLeft size={17}/> Quay lại hành trình</button><div className="bg-white border rounded-3xl overflow-hidden"><div className="p-6 border-b flex justify-between gap-4"><div><div className="flex items-center gap-2 text-cyan-600 font-bold"><CalendarClock/> GIA HẠN HỢP ĐỒNG</div><h1 className="text-2xl font-extrabold text-[#0D1B3E] mt-2">{contract.soHopDong||`Hợp đồng #${contract.id}`}</h1><p className="text-sm text-gray-500">Chỉ áp dụng khi hợp đồng đang thuê và xe không có lịch tiếp theo bị trùng.</p></div><span className="h-fit px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-bold">{contract.trangThai}</span></div><div className="p-6">
 {err&&<div className="mb-4 bg-red-50 border border-red-200 text-red-700 p-4 rounded-xl flex gap-2"><ShieldAlert size={18}/>{err}</div>}{msg&&<div className="mb-4 bg-emerald-50 border border-emerald-200 text-emerald-700 p-4 rounded-xl flex gap-2"><CheckCircle2 size={18}/>{msg}</div>}
 <div className="grid sm:grid-cols-3 gap-3 mb-6"><Box l="Trả hiện tại" v={fmt(contract.thoiGianTraDuKien)}/><Box l="Đơn giá/ngày" v={money(contract.donGiaNgay)}/><Box l="Trạng thái" v="Đang thuê"/></div>
 {latest?.trangThai==='PENDING'?<State title="Đang chờ nhân viên duyệt" text={`Đề nghị trả mới: ${fmt(latest.thoiGianTraMoi)} · ${latest.soNgayGiaHan} ngày · ${money(latest.tienPhatSinh)}`} />:latest?.trangThai==='APPROVED'?<div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-5"><div className="font-bold text-emerald-800 flex gap-2"><CheckCircle2/> Yêu cầu gia hạn đã được duyệt</div><div className="text-sm text-emerald-800 mt-2">Lịch xe đã được giữ đến <b>{fmt(latest.thoiGianTraMoi)}</b>. Phí gia hạn: <b>{money(latest.tienPhatSinh)}</b>.</div><div className="mt-4 bg-white/70 border border-emerald-200 rounded-xl p-3 text-sm text-emerald-800"><b>Không cần thanh toán ngay.</b> Phí gia hạn đã được cộng vào giá trị hợp đồng và sẽ quyết toán một lần khi trả xe.</div></div>:<div className="grid md:grid-cols-2 gap-5"><label><span className="text-sm font-bold">Thời gian trả mới</span><input type="datetime-local" min={localInput(contract.thoiGianTraDuKien)} value={newTime} onChange={e=>setNewTime(e.target.value)} className="mt-2 w-full border rounded-xl p-3"/></label><label><span className="text-sm font-bold">Lý do gia hạn</span><textarea value={reason} onChange={e=>setReason(e.target.value)} rows="3" placeholder="Ví dụ: Tôi cần sử dụng xe thêm..." className="mt-2 w-full border rounded-xl p-3"/></label><div className="md:col-span-2 grid sm:grid-cols-2 gap-3"><Box l="Thời gian gia hạn dự kiến" v={days?`+${days} ngày`:'—'}/><Box l="Phí dự kiến" v={days?money(estimate):'—'}/></div><button disabled={busy||contract.trangThai!=='IN_PROGRESS'} onClick={submit} className="md:col-span-2 bg-cyan-600 disabled:bg-gray-300 text-white py-3.5 rounded-xl font-bold">{busy?'Đang kiểm tra lịch...':'Kiểm tra lịch & gửi yêu cầu gia hạn'}</button></div>}
 {latest?.trangThai==='REJECTED'&&<div className="mt-4 bg-red-50 border border-red-200 text-red-700 rounded-xl p-4">Yêu cầu gia hạn gần nhất đã bị từ chối. Ngày trả của hợp đồng giữ nguyên.</div>}
 </div></div></div></div>;
}
function Box({l,v}){return <div className="bg-[#F6F8FB] rounded-xl p-4"><div className="text-xs text-gray-400">{l}</div><div className="font-bold text-[#0D1B3E] mt-1">{v}</div></div>}
function State({title,text}){return <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5"><div className="font-bold text-amber-800 flex gap-2"><Clock3/> {title}</div><p className="text-sm text-amber-800 mt-2">{text}</p></div>}
