import {useEffect,useState} from "react";
import {ChevronLeft,User,ShieldCheck,CreditCard,Upload,CheckCircle,AlertCircle,Landmark,Save} from "lucide-react";
import {customersApi} from "../../services/api";
export default function ProfilePage({onNavigate}){
 const[p,setP]=useState(null),[f,setF]=useState({}),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false),[pre,setPre]=useState({});
 const load=()=>customersApi.me().then(x=>{setP(x);setF({soDienThoai:x.soDienThoai||"",soCccd:x.soCccd||"",soGplx:x.soGplx||"",diaChi:x.diaChi||"",ngaySinh:x.ngaySinh||"",nganHang:x.nganHang||"",soTaiKhoan:x.soTaiKhoan||"",chuTaiKhoan:x.chuTaiKhoan||""})}).catch(e=>setErr(e.message));
 useEffect(()=>{load()},[]);
 const save=async()=>{try{setBusy(true);setErr("");await customersApi.updateMe(f);setMsg("Đã lưu hồ sơ.");await load()}catch(e){setErr(e.message)}finally{setBusy(false)}};
 const up=async(type,file)=>{if(!file)return;try{setBusy(true);setErr("");setPre(v=>({...v,[type]:URL.createObjectURL(file)}));await customersApi.uploadDocument(type,file);setMsg("Đã tải ảnh giấy tờ. Ảnh mới cần nhân viên xác minh lại.");await load()}catch(e){setErr(e.message)}finally{setBusy(false)}};
 if(!p)return <div className="p-8">{err||"Đang tải hồ sơ..."}</div>;
 const Field=({k,label,type="text"})=><label className="block"><span className="text-xs font-bold text-gray-500">{label}</span><input type={type} value={f[k]||""} onChange={e=>setF({...f,[k]:e.target.value})} className="mt-1 w-full border rounded-xl px-3 py-2.5"/></label>;
 const Doc=({type,title,done,verified})=><div className="border rounded-xl p-4"><div className="flex justify-between"><b>{title}</b><span className={`text-xs font-bold ${verified?"text-emerald-600":"text-amber-600"}`}>{verified?"✓ Đã xác minh":done?"Chờ xác minh":"Chưa tải ảnh"}</span></div>{pre[type]&&<img src={pre[type]} className="mt-3 h-28 rounded-lg object-cover border"/>}<label className="mt-3 inline-flex cursor-pointer items-center gap-2 border rounded-lg px-3 py-2 text-sm font-semibold"><Upload size={15}/> {done?"Thay ảnh":"Tải ảnh"}<input className="hidden" type="file" accept="image/jpeg,image/png" onChange={e=>up(type,e.target.files?.[0])}/></label></div>;
 return <div className="min-h-screen bg-[#F6F8FB]"><div className="max-w-4xl mx-auto p-6"><button onClick={()=>onNavigate("landing")} className="flex gap-1 text-sm text-gray-500 mb-5"><ChevronLeft size={18}/>Trang chủ</button><h1 className="text-2xl font-extrabold text-[#0D1B3E]">Hồ sơ khách hàng</h1><p className="text-sm text-gray-500 mt-1">Thông tin dùng cho thuê xe, xác minh giấy tờ và nhận hoàn tiền.</p>{msg&&<div className="mt-4 bg-emerald-50 text-emerald-700 p-3 rounded-xl">{msg}</div>}{err&&<div className="mt-4 bg-red-50 text-red-700 p-3 rounded-xl">{err}</div>}
 <section className="bg-white border rounded-2xl p-5 mt-5"><h2 className="font-bold flex gap-2"><User size={18}/>Thông tin cá nhân</h2><div className="grid sm:grid-cols-2 gap-4 mt-4"><div><span className="text-xs text-gray-500">Họ tên</span><div className="font-bold mt-1">{p.hoTen}</div></div><div><span className="text-xs text-gray-500">Email</span><div className="font-bold mt-1">{p.email}</div></div><Field k="soDienThoai" label="Số điện thoại"/><Field k="ngaySinh" label="Ngày sinh" type="date"/><div className="sm:col-span-2"><Field k="diaChi" label="Địa chỉ"/></div></div></section>
 <section className="bg-white border rounded-2xl p-5 mt-5"><h2 className="font-bold flex gap-2"><ShieldCheck size={18}/>Hồ sơ thuê xe</h2><div className="grid sm:grid-cols-2 gap-4 mt-4"><Field k="soCccd" label="Số CCCD *"/><Field k="soGplx" label="Số GPLX ô tô *"/></div><div className="grid sm:grid-cols-3 gap-3 mt-4"><Doc type="cccd-front" title="CCCD mặt trước" done={!!p.anhCccdMatTruoc} verified={p.cccdDaXacMinh}/><Doc type="cccd-back" title="CCCD mặt sau" done={!!p.anhCccdMatSau} verified={p.cccdDaXacMinh}/><Doc type="gplx" title="GPLX ô tô" done={!!p.anhGplx} verified={p.gplxDaXacMinh}/></div><div className={`mt-4 p-3 rounded-xl text-sm flex gap-2 ${p.hoSoDaXacMinh?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{p.hoSoDaXacMinh?<CheckCircle size={18}/>:<AlertCircle size={18}/>} {p.hoSoDaXacMinh?"Hồ sơ CCCD và GPLX đã được xác minh.":"Hồ sơ cần đủ ảnh CCCD/GPLX và được nhân viên xác minh trước khi thuê xe online."}</div></section>
 <section className="bg-white border rounded-2xl p-5 mt-5"><h2 className="font-bold flex gap-2"><Landmark size={18}/>Thông tin nhận hoàn tiền</h2><p className="text-xs text-gray-500 mt-1">Chỉ dùng khi hợp đồng phát sinh hoàn tiền.</p><div className="grid sm:grid-cols-3 gap-4 mt-4"><Field k="nganHang" label="Ngân hàng"/><Field k="soTaiKhoan" label="Số tài khoản"/><Field k="chuTaiKhoan" label="Tên chủ tài khoản"/></div></section>
 <button disabled={busy} onClick={save} className="mt-5 bg-[#0D1B3E] text-white rounded-xl px-5 py-3 font-bold flex gap-2"><Save size={17}/>{busy?"Đang xử lý...":"Lưu hồ sơ"}</button></div></div>;
}
