import { useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, Car, ChevronRight, RefreshCw } from "lucide-react";
import { rentalsApi, vehiclesApi } from "../../services/api";

const VN={PENDING:"Chờ duyệt",APPROVED:"Đã duyệt",REJECTED:"Đã từ chối",CANCELLED:"Đã hủy"};
const fmt=v=>v?new Date(v).toLocaleString("vi-VN",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—";
const money=n=>`${Number(n||0).toLocaleString("vi-VN")} ₫`;
export default function RentalHistoryPage({onNavigate}){
 const [rows,setRows]=useState([]),[cars,setCars]=useState([]),[loading,setLoading]=useState(true),[err,setErr]=useState("");
 const load=async()=>{try{setLoading(true);setErr("");const [r,v]=await Promise.all([rentalsApi.discoverMine(),vehiclesApi.list()]);setRows(r);setCars(v)}catch(e){setErr(`${e.status||""} ${e.message||"Không tải được yêu cầu thuê"}`.trim())}finally{setLoading(false)}};
 useEffect(()=>{load();const f=()=>load();window.addEventListener("carrent:remote-update",f);return()=>window.removeEventListener("carrent:remote-update",f)},[]);
 const car=id=>cars.find(x=>Number(x.id)===Number(id));
 return <div className="min-h-screen bg-[#F5F7FB]"><header className="bg-white border-b"><div className="max-w-6xl mx-auto h-16 px-5 flex items-center justify-between"><button onClick={()=>onNavigate("landing")} className="flex gap-2 items-center text-sm text-slate-500"><ArrowLeft size={17}/>Trang chủ</button><b className="text-[#0D1B3E]">CARRENT <span className="text-cyan-500">PRO</span></b></div></header><main className="max-w-6xl mx-auto p-5 sm:p-8"><div className="flex items-end justify-between gap-4 mb-6"><div><div className="text-xs font-bold tracking-[.2em] text-cyan-600">TÀI KHOẢN CỦA TÔI</div><h1 className="text-3xl font-extrabold text-[#0D1B3E] mt-1">Lịch sử yêu cầu thuê</h1><p className="text-slate-500 mt-1">Dữ liệu lấy trực tiếp từ tài khoản đang đăng nhập.</p></div><button onClick={load} className="w-11 h-11 rounded-xl bg-white border flex items-center justify-center text-slate-500"><RefreshCw size={17}/></button></div>{err&&<div className="bg-red-50 border border-red-200 text-red-700 rounded-xl p-4 mb-4">{err}</div>}{loading?<div className="bg-white border rounded-2xl p-10 text-center text-slate-400">Đang tải...</div>:<div className="grid md:grid-cols-2 gap-4">{rows.map(r=>{const v=car(r.idXe);return <button key={r.id} onClick={()=>onNavigate("tracking",r)} className="text-left bg-white border border-slate-200 hover:border-cyan-300 hover:shadow-lg transition rounded-2xl p-5"><div className="flex justify-between gap-3"><div><div className="text-xs text-slate-400">YÊU CẦU #{r.id}</div><h2 className="font-extrabold text-[#0D1B3E] mt-1">{v?.name||`Xe #${r.idXe}`}</h2></div><span className="h-fit px-3 py-1 rounded-full bg-slate-100 text-slate-600 text-xs font-bold">{VN[r.trangThai]||r.trangThai}</span></div><div className="grid sm:grid-cols-2 gap-3 mt-4 text-sm"><div className="bg-slate-50 rounded-xl p-3"><CalendarDays size={15} className="text-cyan-600 mb-1"/><div className="text-slate-400 text-xs">Thời gian</div><div className="font-semibold mt-1">{fmt(r.thoiGianNhan)}<br/>→ {fmt(r.thoiGianTraDuKien)}</div></div><div className="bg-slate-50 rounded-xl p-3"><Car size={15} className="text-cyan-600 mb-1"/><div className="text-slate-400 text-xs">Dự kiến / Cọc</div><div className="font-semibold mt-1">{money(r.tienUocTinh)}<br/><span className="text-cyan-700">Cọc {money(r.tienCoc)}</span></div></div></div><div className="mt-4 flex justify-end text-sm font-bold text-cyan-700 items-center gap-1">Theo dõi hành trình <ChevronRight size={16}/></div></button>})}</div>}{!loading&&!rows.length&&<div className="bg-white border rounded-2xl p-10 text-center text-slate-400">Bạn chưa có yêu cầu thuê xe.</div>}</main></div>
}
