import { useEffect, useMemo, useState } from "react";
import { ChevronLeft, CheckCircle, Car, User } from "lucide-react";
import { customersApi, rentalsApi, vehiclesApi } from "../../services/api";

const fmtMoney=n=>`${Number(n||0).toLocaleString("vi-VN")} ₫`;
export default function StaffOfflineCreate({onBack,onCreated}){
  const [customers,setCustomers]=useState([]),[vehicles,setVehicles]=useState([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false);
  const [form,setForm]=useState({idKhachHang:"",idXe:"",thoiGianNhan:"",thoiGianTraDuKien:""});
  useEffect(()=>{(async()=>{try{const[c,v]=await Promise.all([customersApi.list(),vehiclesApi.list()]);setCustomers(c||[]);setVehicles((v||[]).filter(x=>!["MAINTENANCE","INACTIVE"].includes(x.status)))}catch(e){setError(`${e.status||""} ${e.message}`.trim())}finally{setLoading(false)}})()},[]);
  const customer=useMemo(()=>customers.find(x=>String(x.idKhachHang)===String(form.idKhachHang)),[customers,form.idKhachHang]);
  const vehicle=useMemo(()=>vehicles.find(x=>String(x.id)===String(form.idXe)),[vehicles,form.idXe]);
  const days=useMemo(()=>{if(!form.thoiGianNhan||!form.thoiGianTraDuKien)return 0;return Math.max(1,Math.ceil((new Date(form.thoiGianTraDuKien)-new Date(form.thoiGianNhan))/86400000))},[form.thoiGianNhan,form.thoiGianTraDuKien]);
  const submit=async()=>{try{setSubmitting(true);setError("");const r=await rentalsApi.createOffline({idKhachHang:+form.idKhachHang,idXe:+form.idXe,thoiGianNhan:new Date(form.thoiGianNhan).toISOString(),thoiGianTraDuKien:new Date(form.thoiGianTraDuKien).toISOString()});setMessage(`Đã tạo yêu cầu tại quầy #${r.id} - ${r.trangThai}.`);onCreated?.(r)}catch(e){setError(`${e.status||""} ${e.message}`.trim())}finally{setSubmitting(false)}};
  const cls="w-full px-4 py-3 rounded-xl border border-gray-200 bg-white text-sm outline-none focus:border-cyan-400";
  return <div><div className="flex items-center gap-3 mb-6"><button onClick={onBack} className="flex items-center gap-1 text-gray-500"><ChevronLeft size={18}/> Yêu cầu thuê</button><span className="text-gray-300">/</span><h1 className="text-xl font-bold text-[#0D1B3E]">Tạo yêu cầu tại quầy</h1></div>{error&&<div className="bg-red-50 border border-red-200 text-red-700 p-3 rounded-xl mb-4">{error}</div>}{message&&<div className="bg-emerald-50 border border-emerald-200 text-emerald-700 p-3 rounded-xl mb-4 flex gap-2"><CheckCircle size={17}/>{message}</div>}<div className="grid lg:grid-cols-3 gap-5"><div className="lg:col-span-2 space-y-5"><div className="bg-white rounded-2xl border p-5"><h3 className="font-bold mb-4 flex items-center gap-2"><User size={16} className="text-cyan-500"/>Khách hàng</h3><select className={cls} value={form.idKhachHang} onChange={e=>setForm({...form,idKhachHang:e.target.value})}><option value="">-- Chọn khách hàng --</option>{customers.map(c=><option key={c.idKhachHang} value={c.idKhachHang}>#{c.idKhachHang} · {c.hoTen} · {c.soCccd||"chưa CCCD"}</option>)}</select>{customer&&<div className="mt-3 bg-gray-50 rounded-xl p-3 text-sm text-gray-600">{customer.email} · {customer.cccdDaXacMinh?"CCCD đã xác minh":"CCCD chưa xác minh"}</div>}</div><div className="bg-white rounded-2xl border p-5"><h3 className="font-bold mb-4 flex items-center gap-2"><Car size={16} className="text-cyan-500"/>Xe</h3><select className={cls} value={form.idXe} onChange={e=>setForm({...form,idXe:e.target.value})}><option value="">-- Chọn xe --</option>{vehicles.map(v=><option key={v.id} value={v.id}>#{v.id} · {v.name} · {v.plate||"—"} · {fmtMoney(v.pricePerDay)}/ngày</option>)}</select></div><div className="bg-white rounded-2xl border p-5"><h3 className="font-bold mb-4">Thời gian thuê</h3><div className="grid sm:grid-cols-2 gap-3"><label><span className="text-xs font-semibold text-gray-500">NHẬN XE</span><input type="datetime-local" value={form.thoiGianNhan} onChange={e=>setForm({...form,thoiGianNhan:e.target.value})} className={`${cls} mt-1`}/></label><label><span className="text-xs font-semibold text-gray-500">TRẢ XE</span><input type="datetime-local" value={form.thoiGianTraDuKien} onChange={e=>setForm({...form,thoiGianTraDuKien:e.target.value})} className={`${cls} mt-1`}/></label></div></div></div><div><div className="bg-white rounded-2xl border p-5 sticky top-4"><h3 className="font-bold mb-4">Tóm tắt</h3><div className="space-y-2 text-sm"><Row l="Khách hàng" v={customer?.hoTen||"—"}/><Row l="Xe" v={vehicle?.name||"—"}/><Row l="Số ngày" v={days||"—"}/><Row l="Ước tính" v={fmtMoney(days*(vehicle?.pricePerDay||0))}/></div><button disabled={submitting||!form.idKhachHang||!form.idXe||!form.thoiGianNhan||!form.thoiGianTraDuKien} onClick={submit} className="w-full mt-5 bg-[#0D1B3E] disabled:bg-gray-300 text-white py-3 rounded-xl font-bold">{submitting?"Đang tạo...":"Tạo yêu cầu OFFLINE"}</button></div></div></div></div>
}
function Row({l,v}){return <div className="flex justify-between gap-3"><span className="text-gray-400">{l}</span><b className="text-right">{v}</b></div>}
