// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThueXe.Api.Data;

#nullable disable

namespace ThueXe.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThueXe.Api.Models.HangXe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("HangXe");
                });

            modelBuilder.Entity("ThueXe.Api.Models.LoaiXe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<int>("SoCho")
                        .HasColumnType("integer");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LoaiXes");
                });

            modelBuilder.Entity("ThueXe.Api.Models.Xe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bien_so_xe");

                    b.Property<decimal>("DonGiaNgay")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("don_gia_ngay");

                    b.Property<int?>("HangXeId")
                        .HasColumnType("integer");

                    b.Property<int>("IdHangXe")
                        .HasColumnType("integer")
                        .HasColumnName("id_hang_xe");

                    b.Property<int>("IdLoaiXe")
                        .HasColumnType("integer")
                        .HasColumnName("id_loai_xe");

                    b.Property<int?>("LoaiXeId")
                        .HasColumnType("integer");

                    b.Property<string>("MauXe")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mau_xe");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<int?>("NamSanXuat")
                        .HasColumnType("integer")
                        .HasColumnName("nam_san_xuat");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("BienSoXe")
                        .IsUnique();

                    b.HasIndex("HangXeId");

                    b.HasIndex("IdHangXe");

                    b.HasIndex("IdLoaiXe");

                    b.HasIndex("LoaiXeId");

                    b.ToTable("xe");
                });

            modelBuilder.Entity("ThueXe.Api.Models.Xe", b =>
                {
                    b.HasOne("ThueXe.Api.Models.HangXe", null)
                        .WithMany("Xes")
                        .HasForeignKey("HangXeId");

                    b.HasOne("ThueXe.Api.Models.HangXe", "HangXe")
                        .WithMany()
                        .HasForeignKey("IdHangXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThueXe.Api.Models.LoaiXe", "LoaiXe")
                        .WithMany()
                        .HasForeignKey("IdLoaiXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThueXe.Api.Models.LoaiXe", null)
                        .WithMany("Xes")
                        .HasForeignKey("LoaiXeId");

                    b.Navigation("HangXe");

                    b.Navigation("LoaiXe");
                });

            modelBuilder.Entity("ThueXe.Api.Models.HangXe", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("ThueXe.Api.Models.LoaiXe", b =>
                {
                    b.Navigation("Xes");
                });
#pragma warning restore 612, 618
        }
    }
}
